### ISSUE TITLE
Esc key doesn't close test pane

### ISSUE THREAD

**Issue by adammw** [moxley/atom-ruby-test#15]
Normally I'd expect the escape key to close the Ruby Test pane, similar to how the Find and Replace pane disappears when pressing Escape.

**Comment by denislins** [comment]
I understand that some people might prefer that esc don't close the find panel as well, but I much rather have it closes both the test panel and the find panel than using `cmd-alt-x` :(

This could be an optional feature, that doesn't hurt anyone. Why wasn't #66 accepted?

**Comment by vanboom** [comment]
Something changed recently?  ESC used to close the test panel, and not interfere with the find panel on my system. 

1. click the test panel, hit ESC, the test panel would close, the find panel would remain if it was open
2. click inside the find panel, hit ESC, the find panel would close

This is very intuitive behavior.  But something changed within the last few days... ESC no longer closes the test panel.
:+1:   ESC is the most intuitive way to close the test panel imho.

**Comment by moxley** [comment]
@vanboom Nothing has changed with ruby-test recently. ESC has never closed the ruby-test panel, at least not by design.

**Comment by moxley** [comment]
Regarding the ask for ESC to close the pane, it is not a matter of intuition: ESC is already the key binding for closing the Find pane. By binding ESC to close the ruby-test panel, the Find panel cannot be closed with ESC, ever.

But even if you could fix it so that the Find panel closes with ESC when it's open and also closes ruby-test panel when it's open, what happens when both panes are open? Which one should close? Atom doesn't know which one you wanted closed. Sometimes you want the Find pane closed, sometimes you want the ruby-test pane closed. Maybe you want both. How does Atom decide?

You know, Atom already has a panel that opens and closes with a key binding that is not ESC: the tree view. It toggles open and closed with `cmd+\` (on OS X). I use that sucker all the time. Probably like you with ruby-test, I don't want the tree view pane taking up space on my screen when I'm not using it, so I close it, with `cmd+\`.

You can toggle the ruby-test pane with `cmd-ctrl-x` (OS X) or `ctrl-shift-x` (Win/Linux). If you want, you can configure your keymapping file to toggle the ruby-test pane with ESC, breaking the Find pane in the process.

If someone finds a way to bind ESC to the closing of ruby-test without breaking the Find pane, I will accept a code contribution to do so as long as that behavior is configurable, and it is disabled by default.
