### ISSUE TITLE
click on filename in output pane should open it

### ISSUE THREAD

**Issue by gucki** [moxley/atom-ruby-test#65]
Related to https://github.com/moxley/atom-ruby-test/issues/6

When clicking on a filename, ex. `test.rb:52`, in the output pane, that file should be opened and the cursor moved to that line.

**Comment by dancinglightning** [comment]
So i'm too late, i was just going to suggest this. btw may be a double #7

I tried the package, which is a neat idea.

But this was one of the reasons i won't use it, the other being that in case the test pass, the window should just close automatically. Otherwise switching back/forth to the shell is quicker (with guard set up)

Still, nice package

**Comment by moxley** [comment]
Duplicate of #7
